#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Advanced ML Metrics Plots — Thesis Grade
=========================================
Generates four publication-ready figures that complete the thesis evaluation:

  1. Class Distribution     — recordings + estimated windows per class (train vs test)
  2. CV Fold Scores         — per-fold accuracy scatter, shows model stability
  3. Train / CV / Test Gap  — three-bar grouped chart, visualises generalisation gap
  4. ROC Curves             — one-vs-rest AUC per class, for each requested model

Usage
-----
  python plot_advanced_metrics.py                    # all 4 plots, default paths
  python plot_advanced_metrics.py --save             # save PNG to models/plots/
  python plot_advanced_metrics.py --no-roc           # skip ROC (fast, no model load)
  python plot_advanced_metrics.py --model rf et      # ROC for RF + ET only
  python plot_advanced_metrics.py --no-show --save   # headless / CI mode

Requirements
------------
  metrics.json must have been generated by:
    python csi_ml_pipeline.py --classes walk_activity no_activity --save_model
  (this fills cv_scores, train_accuracy, etc.)
"""

import sys
import argparse
import json
from pathlib import Path

import numpy as np

from csi_parser import configure_console_output
configure_console_output()

from plot_window_utils import setup_matplotlib, show_all
import matplotlib.pyplot as plt

try:
    import joblib
    from data_preprocessing import load_csi_csv
    from csi_ml_pipeline import extract_features_from_window
    import config
except ImportError as e:
    print(f"[ERROR] Missing module: {e}")
    sys.exit(1)


# -----------------------------------------------------------------------
# STYLE
# -----------------------------------------------------------------------

from plot_styles import STYLE, CLASS_COLORS, MODEL_PALETTE, _apply_style


def _save_fig(fig, save_dir: Path, name: str):
    save_dir.mkdir(parents=True, exist_ok=True)
    out = save_dir / f"{name}.png"
    fig.savefig(out, dpi=300, bbox_inches="tight", facecolor=STYLE["bg"])
    print(f"  [SAVE] {out}")


# -----------------------------------------------------------------------
# HELPERS
# -----------------------------------------------------------------------

def _count_frames(filepath: Path) -> int:
    """Count CSI_DATA frames without full parsing — fast line scan."""
    count = 0
    try:
        with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                if line.startswith("CSI_DATA"):
                    count += 1
    except OSError:
        pass
    return count


def _estimate_windows(n_frames: int, window_size: int, step: int) -> int:
    if n_frames < window_size:
        return 0
    return max(0, (n_frames - window_size) // step + 1)


def _load_metrics(json_path: Path) -> dict:
    if not json_path.exists():
        print(f"[ERROR] metrics.json not found: {json_path}")
        print("        Run: python csi_ml_pipeline.py --classes walk_activity no_activity --save_model")
        sys.exit(1)
    with open(json_path, "r", encoding="utf-8") as f:
        return json.load(f)


def _load_cfg(models_dir: Path) -> dict:
    path = models_dir / "experiment_config.json"
    if not path.exists():
        print(f"[WARN] experiment_config.json not found in {models_dir}")
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _build_test_set(cfg: dict, models_dir: Path, data_dir: Path,
                    window_size: int, step: int):
    """
    Rebuild X_test / y_test from saved pipeline + experiment config.
    Used for ROC computation without re-fitting anything.
    Window size and step are read from experiment_config.json when available
    so they always match the original training evaluation exactly.
    """
    # Prefer saved experiment settings over CLI defaults so ROC windows
    # match the exact test set used during training.
    window_size = int(cfg.get("window_size", window_size)) if cfg else window_size
    step        = int(cfg.get("step",        step))        if cfg else step

    pipeline_path = models_dir / "csi_pipeline.joblib"
    le_path       = models_dir / "label_encoder.joblib"

    if not pipeline_path.exists() or not le_path.exists():
        print("[ERROR] csi_pipeline.joblib or label_encoder.joblib not found.")
        return None, None, None

    pipeline = joblib.load(pipeline_path)
    le       = joblib.load(le_path)

    test_files = cfg.get("test_files", {})
    if not test_files:
        print("[WARN] No test_files in experiment_config.json")
        return None, None, le

    X_parts, y_parts = [], []
    for cls_name, files in test_files.items():
        if cls_name not in le.classes_:
            continue
        cls_idx = list(le.classes_).index(cls_name)
        for rel in files:
            fpath = data_dir / rel
            if not fpath.exists():
                print(f"  [SKIP] {fpath} not found")
                continue
            try:
                complex_matrix, _ = load_csi_csv(fpath)
            except Exception as e:
                print(f"  [SKIP] {fpath}: {e}")
                continue
            # Transform the full recording first (matching training: temporal diff
            # reduces length by 1, then PCA+scaler are applied to the full sequence).
            # Slide windows over the already-processed data so each window is
            # (window_size, n_pca) — exactly what the classifier was trained on.
            try:
                proc_full = pipeline.transform(complex_matrix, use_pca=True).astype(np.float64)
            except Exception as e:
                print(f"  [SKIP] {fpath}: transform failed — {e}")
                continue
            n_proc = proc_full.shape[0]
            for s in range(0, n_proc - window_size + 1, step):
                proc = proc_full[s:s + window_size]
                feat = extract_features_from_window(proc, fs=pipeline.fs, cutoff_hz=pipeline.cutoff)
                if np.isfinite(feat).all():
                    X_parts.append(feat)
                    y_parts.append(cls_idx)

    if not X_parts:
        print("[WARN] No valid test windows found.")
        return None, None, le

    return np.array(X_parts), np.array(y_parts), le


# -----------------------------------------------------------------------
# PLOT 1 — CLASS DISTRIBUTION
# -----------------------------------------------------------------------

def plot_class_distribution(
    cfg: dict, data_dir: Path,
    window_size: int, step: int,
    save: bool, save_dir: Path, no_show: bool,
):
    """Recordings and estimated windows per class (train vs test split)."""
    if not cfg:
        print("[SKIP] Class distribution: experiment_config.json not available.")
        return

    train_files = cfg.get("train_files", {})
    test_files  = cfg.get("test_files",  {})
    classes     = cfg.get("classes", sorted(set(list(train_files) + list(test_files))))

    # Count recordings
    rec_train = [len(train_files.get(c, [])) for c in classes]
    rec_test  = [len(test_files.get(c,  [])) for c in classes]

    # Count estimated windows (scan frame counts)
    print("[INFO] Counting frames for window estimation…")
    def _win_count_for_files(files_list):
        total = 0
        for rel in files_list:
            n = _count_frames(data_dir / rel)
            total += _estimate_windows(n, window_size, step)
        return total

    win_train = [_win_count_for_files(train_files.get(c, [])) for c in classes]
    win_test  = [_win_count_for_files(test_files.get(c,  [])) for c in classes]

    _apply_style()
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=config.PLOT_ADVANCED_METRICS_SIZE)
    fig.patch.set_facecolor(STYLE["bg"])

    x     = np.arange(len(classes))
    width = 0.35

    # --- Recordings ---
    bars_tr = ax1.bar(x - width / 2, rec_train, width,
                      label="Train", color=STYLE["a1"], edgecolor="white")
    bars_te = ax1.bar(x + width / 2, rec_test,  width,
                      label="Test",  color=STYLE["a3"], edgecolor="white")
    ax1.set_xticks(x)
    ax1.set_xticklabels([c.capitalize() for c in classes],
                        fontsize=11, fontweight="bold")
    ax1.set_ylabel("Number of Recordings", fontsize=11, fontweight="bold")
    ax1.set_title("Recordings per Class\n(Train / Test Split)",
                  fontsize=12, fontweight="bold")
    ax1.legend(fontsize=10, framealpha=0.9)
    ax1.bar_label(bars_tr, fmt="%d", padding=3, fontweight="bold", fontsize=10)
    ax1.bar_label(bars_te, fmt="%d", padding=3, fontweight="bold", fontsize=10)

    # --- Estimated windows ---
    bars_wtr = ax2.bar(x - width / 2, win_train, width,
                       label="Train", color=STYLE["a1"], edgecolor="white")
    bars_wte = ax2.bar(x + width / 2, win_test,  width,
                       label="Test",  color=STYLE["a3"], edgecolor="white")
    ax2.set_xticks(x)
    ax2.set_xticklabels([c.capitalize() for c in classes],
                        fontsize=11, fontweight="bold")
    ax2.set_ylabel("Estimated Windows", fontsize=11, fontweight="bold")
    ax2.set_title(
        f"Windows per Class\n(window={window_size} frames, step={step} frames)",
        fontsize=12, fontweight="bold")
    ax2.legend(fontsize=10, framealpha=0.9)
    ax2.bar_label(bars_wtr, fmt="%d", padding=3, fontweight="bold", fontsize=10)
    ax2.bar_label(bars_wte, fmt="%d", padding=3, fontweight="bold", fontsize=10)

    # Totals annotation
    total_rec = sum(rec_train) + sum(rec_test)
    total_win = sum(win_train) + sum(win_test)
    fig.suptitle(
        f"Dataset Distribution — {total_rec} recordings total  |  "
        f"~{total_win} windows total  |  {len(classes)} classes",
        fontsize=13, fontweight="bold",
    )
    fig.tight_layout(rect=[0, 0, 1, 0.93])

    if save:
        _save_fig(fig, save_dir, "adv_01_class_distribution")
    if not no_show:
        show_all(figs=[fig])
    plt.close(fig)


# -----------------------------------------------------------------------
# PLOT 2 — CV FOLD SCORES
# -----------------------------------------------------------------------

def plot_cv_fold_scores(
    metrics: dict,
    save: bool, save_dir: Path, no_show: bool,
):
    """Per-fold CV accuracy scatter + mean ± std for every model."""
    # Check if cv_scores exist
    has_folds = any(len(v.get("cv_scores", [])) > 0 for v in metrics.values())
    if not has_folds:
        print("[SKIP] CV fold scores not in metrics.json. Re-run pipeline with "
              "--save_model to generate them.")
        return

    model_names = list(metrics.keys())
    n_models    = len(model_names)

    # Chance level depends on number of classes
    n_classes   = len(next(iter(metrics.values())).get("classes", ["a", "b"]))
    chance_pct  = 100.0 / n_classes

    _apply_style()
    fig, ax = plt.subplots(figsize=(max(9, n_models * 1.4), 6))
    fig.patch.set_facecolor(STYLE["bg"])

    n_folds = 0
    for i, name in enumerate(model_names):
        scores = metrics[name].get("cv_scores", [])
        if not scores:
            continue
        scores  = np.array(scores) * 100
        mean    = scores.mean()
        std     = scores.std()
        color   = MODEL_PALETTE[i % len(MODEL_PALETTE)]
        n_folds = len(scores)

        # Individual fold dots (jittered so they don't overlap)
        jitter = np.random.default_rng(seed=i).uniform(-0.18, 0.18, n_folds)
        ax.scatter(np.full(n_folds, i) + jitter, scores,
                   color=color, s=60, zorder=3, alpha=0.85, edgecolors="white",
                   linewidth=0.5)

        # Mean bar (translucent)
        ax.bar(i, mean, width=0.55, color=color, alpha=0.25,
               edgecolor=color, linewidth=1.5, zorder=1)

        # Error bar (±1 std)
        ax.errorbar(i, mean, yerr=std, fmt="none",
                    ecolor=color, elinewidth=2.5, capsize=6, capthick=2.5,
                    zorder=4)

        # Mean label
        ax.text(i, mean + std + 0.8, f"{mean:.1f}%",
                ha="center", va="bottom", fontsize=9, fontweight="bold",
                color=color)

    ax.set_xticks(range(n_models))
    ax.set_xticklabels(model_names, fontsize=10, fontweight="bold", rotation=20,
                       ha="right")
    ax.set_ylabel("CV Accuracy (%)", fontsize=11, fontweight="bold")
    ax.set_ylim(max(0, ax.get_ylim()[0] - 5), min(105, ax.get_ylim()[1] + 8))
    # Prefer the stored splitter name from metrics.json; fall back gracefully.
    splitter_names = {v.get("cv_splitter") for v in metrics.values()
                      if v.get("cv_splitter")}
    splitter_label = splitter_names.pop() if len(splitter_names) == 1 else "GroupKFold"
    ax.set_title(
        f"Cross-Validation Fold Scores  ({n_folds}-Fold {splitter_label})\n"
        "Dots = individual folds  |  Bar = mean  |  Error bar = ±1 std",
        fontsize=12, fontweight="bold",
    )
    ax.axhline(chance_pct, color=STYLE["grid"], linewidth=1, linestyle="--")
    ax.text(n_models - 0.5, chance_pct + 0.5,
            f"Chance ({chance_pct:.0f}%)", fontsize=8,
            color="#888888", ha="right")

    fig.tight_layout()

    if save:
        _save_fig(fig, save_dir, "adv_02_cv_fold_scores")
    if not no_show:
        show_all(figs=[fig])
    plt.close(fig)


# -----------------------------------------------------------------------
# PLOT 3 — TRAIN / CV / TEST GAP
# -----------------------------------------------------------------------

def plot_train_cv_test_gap(
    metrics: dict,
    save: bool, save_dir: Path, no_show: bool,
):
    """Grouped bars: Train accuracy, CV mean, Test accuracy per model."""
    model_names = list(metrics.keys())
    n_models    = len(model_names)

    has_train = any("train_accuracy" in v for v in metrics.values())

    _apply_style()
    fig, ax = plt.subplots(figsize=(max(9, n_models * 1.6), 6))
    fig.patch.set_facecolor(STYLE["bg"])

    x     = np.arange(n_models)
    n_grp = 3 if has_train else 2
    width = 0.22 if has_train else 0.3
    offsets = np.linspace(-(n_grp - 1) * width / 2,
                           (n_grp - 1) * width / 2, n_grp)
    # offsets[0] = leftmost, offsets[-1] = rightmost — always explicit
    # 3-bar layout: [Train, CV, Test] at offsets[0,1,2]
    # 2-bar layout: [CV,    Test]     at offsets[0,1]
    cv_off   = offsets[1] if has_train else offsets[0]
    test_off = offsets[2] if has_train else offsets[1]

    cv_means  = np.array([metrics[m].get("cv_accuracy_mean", 0) * 100
                          for m in model_names])
    cv_stds   = np.array([metrics[m].get("cv_accuracy_std",  0) * 100
                          for m in model_names])
    test_accs = np.array([metrics[m].get("test_accuracy", 0) * 100
                          for m in model_names])

    bar_sets = []

    if has_train:
        train_accs = np.array([metrics[m].get("train_accuracy", 0) * 100
                               for m in model_names])
        b_tr = ax.bar(x + offsets[0], train_accs, width,
                      label="Train Accuracy (non-aug)",
                      color=STYLE["a3"], edgecolor="white", alpha=0.9)
        bar_sets.append((b_tr, train_accs))

    b_cv = ax.bar(x + cv_off, cv_means, width,
                  label="CV Accuracy (mean ± std)",
                  color=STYLE["a1"], edgecolor="white", alpha=0.9)
    ax.errorbar(x + cv_off, cv_means, yerr=cv_stds, fmt="none",
                ecolor="#1e3a8a", elinewidth=1.8, capsize=5, capthick=1.8,
                zorder=5)
    bar_sets.append((b_cv, cv_means))

    b_te = ax.bar(x + test_off, test_accs, width,
                  label="Test Accuracy",
                  color=STYLE["a4"], edgecolor="white", alpha=0.9)
    bar_sets.append((b_te, test_accs))

    # Value labels on top of every bar
    for bars, vals in bar_sets:
        for bar, val in zip(bars, vals):
            ax.text(bar.get_x() + bar.get_width() / 2,
                    bar.get_height() + 0.8,
                    f"{val:.1f}%",
                    ha="center", va="bottom",
                    fontsize=8, fontweight="bold")

    ax.set_xticks(x)
    ax.set_xticklabels(model_names, fontsize=10, fontweight="bold",
                       rotation=20, ha="right")
    ax.set_ylabel("Accuracy (%)", fontsize=11, fontweight="bold")
    ax.set_ylim(0, 115)
    ax.set_title(
        "Generalisation Gap — Train / CV / Test Accuracy\n"
        "Gap between CV and Test reflects dataset size (will close with 100 recordings)",
        fontsize=12, fontweight="bold",
    )
    ax.legend(fontsize=10, framealpha=0.9, loc="lower right")

    fig.tight_layout()

    if save:
        _save_fig(fig, save_dir, "adv_03_train_cv_test_gap")
    if not no_show:
        show_all(figs=[fig])
    plt.close(fig)


# -----------------------------------------------------------------------
# PLOT 4 — ROC CURVES
# -----------------------------------------------------------------------

def plot_roc_curves(
    metrics: dict, models_dir: Path, data_dir: Path, cfg: dict,
    window_size: int, step: int,
    target_models: list,
    save: bool, save_dir: Path, no_show: bool,
):
    """One-vs-rest ROC curves with AUC for each requested model."""
    from sklearn.metrics import roc_curve, auc
    from sklearn.preprocessing import label_binarize

    print("\n[INFO] Building test set for ROC computation…")
    X_test, y_test, le = _build_test_set(cfg, models_dir, data_dir,
                                         window_size, step)
    if X_test is None:
        print("[SKIP] ROC curves: could not build test set.")
        return

    classes   = list(le.classes_)
    n_classes = len(classes)

    if n_classes < 2:
        print("[SKIP] ROC curves: need at least 2 classes in the test set.")
        return

    # Determine which models to plot
    if target_models and target_models != ["all"]:
        keys = [k for k in target_models if k in config.MODEL_FILES]
    else:
        keys = list(config.MODEL_FILES.keys())

    # Load requested models
    loaded = {}
    for key in keys:
        path = models_dir / config.MODEL_FILES[key]
        if not path.exists():
            print(f"  [SKIP] {path.name} not found")
            continue
        try:
            m = joblib.load(path)
            if hasattr(m, "n_features_in_") and m.n_features_in_ != X_test.shape[1]:
                print(f"  [SKIP] {key}: feature mismatch "
                      f"({m.n_features_in_} vs {X_test.shape[1]}) — re-train first")
                continue
            loaded[key] = m
        except Exception as e:
            print(f"  [SKIP] {key}: {e}")

    if not loaded:
        print("[SKIP] ROC curves: no valid models found.")
        return

    # Binarize labels for OvR
    y_bin = label_binarize(y_test, classes=list(range(n_classes)))
    if n_classes == 2:
        y_bin = np.hstack([1 - y_bin, y_bin])  # ensure shape (N, 2)

    _apply_style()

    # Layout: one subplot per class, repeated for each model
    # If many models: separate figure per model; else stack subplots
    for model_key, model in loaded.items():
        display_name = next(
            (k for k in metrics if k.lower().replace(" ", "").replace("(", "")
             .replace(")", "") == model_key.lower()), model_key.upper()
        )

        # Compute probabilities or decision scores
        if hasattr(model, "predict_proba"):
            y_score = model.predict_proba(X_test)
        elif hasattr(model, "decision_function"):
            raw = model.decision_function(X_test)
            if raw.ndim == 1:
                raw = np.column_stack([-raw, raw])
            # Softmax-like normalisation for comparability
            raw -= raw.min(axis=1, keepdims=True)
            denom = raw.sum(axis=1, keepdims=True)
            denom[denom == 0] = 1
            y_score = raw / denom
        else:
            print(f"  [SKIP] {model_key}: no predict_proba or decision_function")
            continue

        if y_score.shape[1] != n_classes:
            print(f"  [SKIP] {model_key}: score shape mismatch")
            continue

        _h = config.PLOT_ADVANCED_METRICS_SIZE[1]
        fig, axes = plt.subplots(1, n_classes,
                                  figsize=(5.5 * n_classes, _h))
        fig.patch.set_facecolor(STYLE["bg"])
        if n_classes == 1:
            axes = [axes]
        axes = np.array(axes).flatten()

        for cls_i, cls_name in enumerate(classes):
            ax = axes[cls_i]
            color = CLASS_COLORS[cls_i % len(CLASS_COLORS)]

            fpr, tpr, _ = roc_curve(y_bin[:, cls_i], y_score[:, cls_i])
            roc_auc     = auc(fpr, tpr)

            ax.plot(fpr, tpr, color=color, linewidth=2.5,
                    label=f"AUC = {roc_auc:.3f}")
            ax.fill_between(fpr, tpr, alpha=0.12, color=color)
            ax.plot([0, 1], [0, 1], color=STYLE["grid"],
                    linewidth=1.2, linestyle="--", label="Random")

            ax.set_xlim([-0.02, 1.02])
            ax.set_ylim([-0.02, 1.05])
            ax.set_xlabel("False Positive Rate", fontsize=10, fontweight="bold")
            ax.set_ylabel("True Positive Rate", fontsize=10, fontweight="bold")
            ax.set_title(
                f"ROC — {cls_name.capitalize()} (one-vs-rest)\nAUC = {roc_auc:.3f}",
                fontsize=11, fontweight="bold",
            )
            ax.legend(fontsize=9, loc="lower right", framealpha=0.9)

            # Annotate optimal threshold (top-left corner proximity)
            dist   = np.sqrt(fpr ** 2 + (1 - tpr) ** 2)
            opt_i  = np.argmin(dist)
            ax.plot(fpr[opt_i], tpr[opt_i], "o",
                    color=color, markersize=8, zorder=5,
                    label=f"Optimal threshold")
            ax.annotate(
                f"  ({fpr[opt_i]:.2f}, {tpr[opt_i]:.2f})",
                xy=(fpr[opt_i], tpr[opt_i]), fontsize=8, color=color,
            )

        # Mean AUC in suptitle
        aucs = []
        for cls_i in range(n_classes):
            fpr_i, tpr_i, _ = roc_curve(y_bin[:, cls_i], y_score[:, cls_i])
            aucs.append(auc(fpr_i, tpr_i))
        mean_auc = np.mean(aucs)

        fig.suptitle(
            f"ROC Curves — {display_name}  (One-vs-Rest)\n"
            f"Mean AUC = {mean_auc:.3f}  |  Test samples: {len(y_test)}",
            fontsize=13, fontweight="bold",
        )
        fig.tight_layout(rect=[0, 0, 1, 0.93])

        if save:
            _save_fig(fig, save_dir,
                      f"adv_04_roc_{model_key}")
        if not no_show:
            show_all(figs=[fig])
        plt.close(fig)
        print(f"  [ROC] {display_name}: mean AUC = {mean_auc:.3f}")


# -----------------------------------------------------------------------
# MAIN
# -----------------------------------------------------------------------

def main():
    defaults = config.get_script_defaults("plot_advanced_metrics")
    parser = argparse.ArgumentParser(
        description="Advanced ML metrics plots for CSI HAR thesis"
    )
    parser.add_argument("--json-path",   type=str,
                        default=defaults["json_path"])
    parser.add_argument("--models-dir",  type=str, default=defaults["models_dir"])
    parser.add_argument("--out-dir",     type=str, default=defaults["out_dir"])
    parser.add_argument("--window-size", type=int,
                        default=defaults["window_size"])
    parser.add_argument("--step",        type=int,
                        default=defaults["step"])
    parser.add_argument("--model",       nargs="+",
                        default=defaults["model"],
                        help="Models for ROC: rf svm et knn lr gb mlp nb  "
                             "(default: all)")
    config.add_bool_argument(
        parser,
        dest="roc",
        default=defaults["roc"],
        help="Generate ROC curves (disabling this skips model loading).",
        positive_flags=["--roc"],
        negative_flags=["--no-roc"],
    )
    config.add_bool_argument(
        parser,
        dest="save",
        default=defaults["save"],
        help="Save all figures as PNG (300 DPI)",
        positive_flags=["--save"],
        negative_flags=["--no-save"],
    )
    config.add_bool_argument(
        parser,
        dest="show",
        default=defaults["show"],
        help="Open plot windows when a GUI backend is available.",
        positive_flags=["--show"],
        negative_flags=["--no-show"],
    )
    args = parser.parse_args()
    setup_matplotlib()

    models_dir = Path(args.models_dir)
    json_path  = Path(args.json_path)
    save_dir   = Path(args.out_dir) if args.out_dir else models_dir / "plots"

    print("\n" + "=" * 60)
    print("  ADVANCED ML METRICS")
    print("=" * 60)

    metrics = _load_metrics(json_path)
    cfg     = _load_cfg(models_dir)

    data_dir_str = cfg.get("data_dir", config.DATASETS_DIR)
    data_dir     = Path(data_dir_str)
    if not data_dir.exists():
        data_dir = Path(config.DATASETS_DIR)

    print(f"  Models   : {list(metrics.keys())}")
    print(f"  Classes  : {cfg.get('classes', '?')}")
    print(f"  Data dir : {data_dir}")
    print(f"  Save     : {args.save}  →  {save_dir}")
    print()

    # -- 1. Class Distribution ----------------------------------------
    print("[PLOT 1] Class Distribution")
    plot_class_distribution(
        cfg, data_dir, args.window_size, args.step,
        args.save, save_dir, not args.show,
    )

    # -- 2. CV Fold Scores --------------------------------------------
    print("[PLOT 2] CV Fold Scores")
    plot_cv_fold_scores(metrics, args.save, save_dir, not args.show)

    # -- 3. Train / CV / Test Gap ------------------------------------
    print("[PLOT 3] Train / CV / Test Gap")
    plot_train_cv_test_gap(metrics, args.save, save_dir, not args.show)

    # -- 4. ROC Curves -----------------------------------------------
    if not args.roc:
        print("[SKIP] ROC curves (--no-roc flag set)")
    else:
        print("[PLOT 4] ROC Curves")
        plot_roc_curves(
            metrics, models_dir, data_dir, cfg,
            args.window_size, args.step,
            args.model,
            args.save, save_dir, not args.show,
        )

    print("\n[DONE] All plots generated.")
    if args.save:
        print(f"        Saved to: {save_dir.resolve()}")


if __name__ == "__main__":
    from logging_setup import setup_run_log
    setup_run_log(__file__)
    main()
